# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Heidelberger-Welch Metric Calculation with Stepwise Discard Ratios and Stationarity Test
NULL

heidelWelchMetric <- function(x, alpha = 0.05, eps = 0.1, test_type = "ks") {
    .Call(`_ADVHEIDEL_heidelWelchMetric`, x, alpha, eps, test_type)
}

